-- SQLite
SELECT * FROM COMPANY;

SELECT ID,NAME,SALARY FROM COMPANY;

INSERT INTO OLD_COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
    SELECT ID,NAME,AGE,ADDRESS,SALARY
        FROM COMPANY;

DELETE FROM OLD_COMPANY WHERE ID = 23;
SELECT * FROM OLD_COMPANY;

