-- SQLite

-- DROP TABLE COMPANY;
DROP TABLE OLD_COMPANY;

-- CREATE TABLE COMPANY(
--     ID REAL NOT NULL,
--     NAME TEXT NOT NULL,
--     AGE REAL NOT NULL,
--     ADDRESS TEXT,
--     SALARY REAL
-- );


CREATE TABLE OLD_COMPANY(
    ID REAL NOT NULL,
    NAME TEXT NOT NULL,
    AGE REAL NOT NULL,
    ADDRESS TEXT,
    SALARY REAL
); 

-- CREATE TABLE DEPARTMENT(
--     ID REAL NOT NULL,
--     DEPT TEXT NOT NULL,
--     EMP_ID REAL NOT NULL
-- );


-- INSERT INTO COMPANY VALUES (1,'Paul',32,'California',20000.00);
-- INSERT INTO COMPANY VALUES (2,'Allen',25,'Texas',15000.00);
-- INSERT INTO COMPANY VALUES (3,'Teddy',23,'Norway',20000.00);
-- INSERT INTO COMPANY VALUES (4,'Mark',25,'Rich-Mond',65000.00);
-- INSERT INTO COMPANY VALUES (5,'David',27,'Texas',85000.00);
-- INSERT INTO COMPANY VALUES (6,'Kim',22,'South-Hall',45000.00);
-- INSERT INTO COMPANY VALUES (6,'James',24,'Houston',10000.00);
-- INSERT INTO COMPANY VALUES (10,'Smith',25,'Texas',350000.00);

--INSERT INTO OLD_COMPANY VALUES (1,'Paul',32,'California',20000.00);

INSERT INTO OLD_COMPANY VALUES (1,'Paul',32,'California',20000.00);
-- INSERT INTO OLD_COMPANY VALUES (2,'Allen',25,'Texas',15000.00);
-- INSERT INTO OLD_COMPANY VALUES (3,'Teddy',23,'Norway',20000.00);
-- INSERT INTO OLD_COMPANY VALUES (6,'Kim',22,'South-Hall',45000.00);
INSERT INTO OLD_COMPANY VALUES (7,'James',24,'Houston',10000.00);
-- company 갯수 * department 갯수 7*5
SELECT COMPANY.*,DEPARTMENT.*
FROM COMPANY CROSS JOIN DEPARTMENT;


SELECT EMP_ID,NAME,DEPT
FROM COMPANY INNER JOIN DEPARTMENT ON COMPANY.ID = DEPARTMENT.ID;

--3개 테이블 이너조인
SELECT EMP_ID,COMPANY.NAME,DEPT,OLD_COMPANY.NAME
FROM COMPANY INNER JOIN DEPARTMENT ON COMPANY.ID = DEPARTMENT.EMP_ID
INNER JOIN OLD_COMPANY ON COMPANY.ID = OLD_COMPANY.ID;
    
-- LEFT 조인

SELECT * FROM DEPARTMENT;

SELECT COMPANY.ID, COMPANY.NAME, DEPARTMENT.EMP_ID
FROM COMPANY LEFT OUTER JOIN DEPARTMENT
ON COMPANY.ID=DEPARTMENT.ID;

--

SELECT COMPANY.ID, COMPANY.NAME, OLD_COMPANY.NAME
FROM COMPANY LEFT OUTER JOIN OLD_COMPANY
ON COMPANY.ID=OLD_COMPANY.ID;

--

SELECT * FROM DEPARTMENT;
SELECT * FROM COMPANY;
SELECT * FROM COMPANY WHERE SALARY >20000;


SELECT COMP.NAME, AGE, DEPT, EMP_ID
FROM(SELECT * FROM COMPANY WHERE SALARY >20000) AS COMP
LEFT OUTER JOIN DEPARTMENT
ON COMP.ID=DEPARTMENT.ID;


-- UNION

SELECT EMP_ID, NAME, DEPT FROM COMPANY
INNER JOIN DEPARTMENT ON COMPANY.ID = DEPARTMENT.EMP_ID;

SELECT EMP_ID, NAME,DEPT FROM COMPANY
LEFT OUTER JOIN DEPARTMENT ON COMPANY.ID = DEPARTMENT.EMP_ID;

SELECT EMP_ID, NAME, DEPT FROM COMPANY
INNER JOIN DEPARTMENT ON COMPANY.ID = DEPARTMENT.EMP_ID
UNION
SELECT EMP_ID, NAME,DEPT FROM COMPANY
LEFT OUTER JOIN DEPARTMENT ON COMPANY.ID = DEPARTMENT.EMP_ID;

SELECT EMP_ID, NAME, DEPT FROM COMPANY
INNER JOIN DEPARTMENT ON COMPANY.ID = DEPARTMENT.EMP_ID
UNION ALL
SELECT EMP_ID, NAME,DEPT FROM COMPANY
LEFT OUTER JOIN DEPARTMENT ON COMPANY.ID = DEPARTMENT.EMP_ID;


CREATE VIEW COMAPNY_VIEW AS
    SELECT ID, NAME, AGE
    FROM COMPANY;


SELECT NAME,ADDRESS,
    CASE NAME 
        WHEN 'Paul' THEN SALARY
        WHEN 'David' THEN AGE
        ELSE 'ETC'
    END AS NAME_CASE
FROM COMPANY;


SELECT * FROM COMPANY;

SELECT ID,MAX(NAME) AS NAME,ADDRESS,
    CASE
        WHEN NAME == 'Paul' THEN SALARY
    END AS NAME01_CASE,
    CASE
        WHEN NAME == 'Smith' THEN AGE
    END AS NAME02_CASE
FROM COMPANY GROUP BY ADDRESS;


--

SELECT * FROM COMPANY
WHERE ID IN (SELECT ID 
             FROM COMPANY 
             WHERE SALARY> 45000);



SELECT AGE FROM COMPANY
WHERE EXISTS(SELECT AGE 
             FROM COMPANY AS SUB_COMPANY
             WHERE COMPANY.ID = SUB_COMPANY.ID AND SALARY> 65000);

INSERT INTO COMPANY_BKp
SELECT * FROM COMPANY
WHERE ID IN (SELECT ID FROM COMPANY);
--
DROP TABLE COMPANY_BKp;

CREATE TABLE COMPANY_BKp(
    ID REAL NOT NULL,
    NAME TEXT NOT NULL,
    AGE REAL NOT NULL,
    ADDRESS TEXT NULL,
    SALARY REAL NULL
);

INSERT INTO COMPANY_BKp
SELECT *
FROM COMPANY;
-- subqueries update

UPDATE COMPANY
SET SALARY = SALARY * 0.50
WHERE AGE IN (SELECT AGE FROM COMPANY_BKp WHERE AGE>=27);

SELECT *
FROM COMPANY;

SELECT *
FROM COMPANY_BKp;

-- subqueries delete

DELETE FROM COMPANY
WHERE AGE IN (SELECT AGE FROM COMPANY_BKp WHERE AGE>27);


--Date

SELECT date('now');

SELECT date('now','start of month','+1 month','-1 day');

SELECT datetime(1092941466,'unixepoch');

SELECT datetime(2092941466,'unixepoch');

SELECT datetime(1092941466,'unixepoch','localtime');

SELECT strftime('%s','now');

SELECT strftime('%s','now')
-strftime('%s','2004-01-01 02:34:56');

SELECT date('now','start of year','+9 months','weekday 2');

SELECT time('12:00','localtime');

SELECT time('12:00','utc');
