-- SQLite
-- SELECT index, 지역, 진함, 상호명, 사업장연락처,
-- 사업장주소, 영업시간, 제공품목, 제공대상1, 제공대상2,
-- 후원회원참여여부, 월정기후원, 제공대상2_1, 제공대상2_2, 
-- 제공대상2_3, 제공대상2_4
-- FROM `goodinfluence_table`;


DROP TABLE SHOPINFO;
DROP TABLE SERVICETARGET_1;
DROP TABLE SERVICETARGET_2;
DROP TABLE TARGET;

-- SHOPINFO
CREATE TABLE SHOPINFO
(
  SHOPINFO_ID  REAL NOT NULL,
  OWNERNAME    TEXT NULL    ,
  SHOPNAME     TEXT NULL    ,
  ADDRESS      TEXT NULL    ,
  WORKINGHOURS TEXT NULL    ,
  TELEPHONE    TEXT NULL    ,
  PRIMARY KEY (SHOPINFO_ID)
);

INSERT INTO SHOPINFO
SELECT `index`, 진함, 상호명,사업장주소, 영업시간,사업장연락처
FROM goodinfluence_table;

-- SERVICETARGET_1

SELECT goodinfluence_table.`index` AS ST1_ID,goodinfluence_table.제공대상1,SHOPINFO.SHOPINFO_ID
FROM goodinfluence_table,SHOPINFO
GROUP BY goodinfluence_table.`index`;

CREATE TABLE SERVICETARGET_1
(
  ST1_ID      TEXT NOT NULL,
  TARGET      TEXT NULL    ,
  SHOPINFO_ID REAL NOT NULL,
  PRIMARY KEY (ST1_ID),
  CONSTRAINT FK_SHOPINFO_TO_SERVICETARGET_1
  FOREIGN KEY (SHOPINFO_ID)
  REFERENCES SHOPINFO (SHOPINFO_ID)
);

INSERT INTO SERVICETARGET_1
SELECT goodinfluence_table.`index` AS ST1_ID,goodinfluence_table.제공대상1,SHOPINFO.SHOPINFO_ID
FROM goodinfluence_table,SHOPINFO
GROUP BY goodinfluence_table.`index`;


-- SERVICETARGET_2

SELECT SHOPINFO.SHOPINFO_ID AS STD2_ID,SHOPINFO.SHOPINFO_ID  
FROM SHOPINFO
GROUP BY SHOPINFO.SHOPINFO_ID;

CREATE TABLE SERVICETARGET_2
(
  ST2_ID      TEXT NOT NULL,
  SHOPINFO_ID REAL NOT NULL,
  PRIMARY KEY (ST2_ID),
  CONSTRAINT FK_SHOPINFO_TO_SERVICETARGET_2
  FOREIGN KEY (SHOPINFO_ID)
  REFERENCES SHOPINFO (SHOPINFO_ID)
);

INSERT INTO SERVICETARGET_2
SELECT SHOPINFO.SHOPINFO_ID AS STD2_ID,SHOPINFO.SHOPINFO_ID  
FROM SHOPINFO
GROUP BY SHOPINFO.SHOPINFO_ID;

-- TARGET
-- ERD 설계를 잘못하였다.

CREATE TABLE TARGET
(
  TARGET_ID  TEXT NOT NULL,
  TARGETNAME TEXT NULL        
);

-- CREATE TABLE TARGET_dump
-- (
--   ST2_ID     TEXT NOT NULL,
--   TARGETNAME TEXT NULL    ,  
--   TARGET_ID  TEXT NOT NULL 
-- );

-- INSERT INTO TARGET_dump
-- SELECT DISTINCT target_table.`index` AS ST2_ID,target_table.target,target_table.`index` 
-- FROM target_table,SERVICETARGET_2;


-- SELECT TARGET_dump.rowid
-- FROM TARGET_dump;

-- INSERT INTO TARGET
-- SELECT DISTINCT target_table.`index` AS ST2_ID,target_table.target,TARGET_dump.rowid 
-- FROM target_table,TARGET_dump
-- GROUP BY target_table.`index`,TARGET_dump.rowid;

INSERT INTO TARGET
SELECT DISTINCT target_table.`index` AS TARGET_ID,target_table.target
FROM target_table;

CREATE TABLE SPONSER
(
  SPONSER_ID  TEXT NOT NULL,
  YESORNO     TEXT NULL    ,
  SHOPINFO_ID REAL NOT NULL,
  PRIMARY KEY (SPONSER_ID),
  CONSTRAINT FK_SHOPINFO_TO_SPONSER
  FOREIGN KEY (SHOPINFO_ID)
  REFERENCES SHOPINFO (SHOPINFO_ID)
);
INSERT INTO SPONSER
SELECT goodinfluence_table.`index` AS SPONSER_ID,goodinfluence_table.후원회원참여여부,SHOPINFO.SHOPINFO_ID
FROM goodinfluence_table,SHOPINFO
GROUP BY goodinfluence_table.`index`;

--

CREATE TABLE SPONSERSHIP_MONTHLY
(
  SPONSERSHIP_ID TEXT NOT NULL,
  DONATION       TEXT NULL    ,
  SPONSER_ID     TEXT NOT NULL,
  PRIMARY KEY (SPONSERSHIP_ID),
  CONSTRAINT FK_SPONSER_TO_SPONSERSHIP_MONTHLY
  FOREIGN KEY (SPONSER_ID)
  REFERENCES SPONSER (SPONSER_ID)
);

INSERT INTO SPONSERSHIP_MONTHLY
SELECT goodinfluence_table.`index` AS SPONSER_ID,goodinfluence_table.월정기후원,SPONSER.SPONSER_ID
FROM goodinfluence_table,SPONSER
GROUP BY goodinfluence_table.`index`;
--
CREATE TABLE AREA
(
  AREA_ID     TEXT NOT NULL,
  AREA        TEXT NULL    ,
  SHOPINFO_ID REAL NOT NULL,
  PRIMARY KEY (AREA_ID),
  CONSTRAINT FK_SHOPINFO_TO_AREA
  FOREIGN KEY (SHOPINFO_ID)
  REFERENCES SHOPINFO (SHOPINFO_ID)
);

INSERT INTO AREA
SELECT goodinfluence_table.`index` AS AREA_ID,goodinfluence_table.지역,SHOPINFO.SHOPINFO_ID
FROM goodinfluence_table,SHOPINFO
GROUP BY goodinfluence_table.`index`;

--
CREATE TABLE MENU
(
  MENU_ID     TEXT NOT NULL,
  MENUTYPE    TEXT NULL    ,
  SHOPINFO_ID REAL NOT NULL,
  PRIMARY KEY (MENU_ID),
  CONSTRAINT FK_SHOPINFO_TO_MENU
  FOREIGN KEY (SHOPINFO_ID)
   REFERENCES SHOPINFO (SHOPINFO_ID)
);

CREATE TABLE MENU_index
(
  MENU_ID     TEXT NOT NULL,
  MENUTYPE    TEXT NULL    ,
  SHOPINFO_ID REAL NOT NULL
);

INSERT INTO MENU_index
SELECT goodinfluence_table.`index` AS MENU_ID,goodinfluence_table.제공품목,SHOPINFO.SHOPINFO_ID
FROM goodinfluence_table,SHOPINFO
GROUP BY goodinfluence_table.`index`;

--*****
DROP TABLE MENU;

INSERT INTO MENU
SELECT DISTINCT MENU_index.rowid AS MENU_ID,MENU_index.MENUTYPE,SHOPINFO.SHOPINFO_ID
FROM MENU_index,SHOPINFO
WHERE MENU_ID = SHOPINFO.SHOPINFO_ID;

--