-- SQLite

DROP TABLE ATTACHFILE;
DROP TABLE AUTHORITY;
DROP TABLE HOBBY;
DROP TABLE LOGHISTORY;
DROP TABLE MEMBER;
DROP TABLE MEMBER_HOBBY;
DROP TABLE MEMBER_AUTHORITY;
DROP TABLE MULTIBOARD;
DROP TABLE ORGANIZATION;
DROP TABLE PROJECTS;
DROP TABLE TEACHER;

CREATE TABLE ATTACHFILE
(
  ATTACHFILE_ID TEXT NOT NULL,
  FILENAME      TEXT NULL    ,
  MEM_MB_ID     TEXT NULL    ,
  MULTIBOARD_ID TEXT NOT NULL,
  PRIMARY KEY (ATTACHFILE_ID),
  CONSTRAINT FK_MULTIBOARD_TO_ATTACHFILE
  FOREIGN KEY (MULTIBOARD_ID)
  REFERENCES MULTIBOARD (MULTIBOARD_ID)
);

CREATE TABLE AUTHORITY
(
  AUTHORITY_ID TEXT NOT NULL,
  NAME         TEXT NULL    ,
  PRIMARY KEY (AUTHORITY_ID)
);

CREATE TABLE HOBBY
(
  HOBBY_SEQ TEXT NOT NULL,
  NAME      TEXT NULL    ,
  PRIMARY KEY (HOBBY_SEQ)
);

CREATE TABLE LOGHISTORY
(
  LOGINTIME      TEXT NULL    ,
  LOGHISTORY_SEQ TEXT NOT NULL,
  LOGOUTIME      TEXT NULL    ,
  MEMBER_ID      TEXT NOT NULL,
  PRIMARY KEY (LOGHISTORY_SEQ),
  CONSTRAINT FK_MEMBER_TO_LOGHISTORY
  FOREIGN KEY (MEMBER_ID)
  REFERENCES MEMBER (MEMBER_ID)
);

CREATE TABLE MEMBER
(
  MEMBER_ID        TEXT NOT NULL,
  EMAIL            TEXT NULL    ,
  NAME             TEXT NULL    ,
  PHEONNUMBER      TEXT NULL    ,
  ORGANIZATION_SEQ REAL NOT NULL,
  PRIMARY KEY (MEMBER_ID),
  CONSTRAINT FK_ORGANIZATION_TO_MEMBER
  FOREIGN KEY (ORGANIZATION_SEQ)
  REFERENCES ORGANIZATION (ORGANIZATION_SEQ)
);

CREATE TABLE MEMBER_AUTHORITY
(
  AUTHORITY_ID TEXT NOT NULL,
  MEMBER_ID    TEXT NOT NULL,
  CONSTRAINT FK_AUTHORITY_TO_MEMBER_AUTHORITY
  FOREIGN KEY (AUTHORITY_ID)
  REFERENCES AUTHORITY (AUTHORITY_ID),
  CONSTRAINT FK_MEMBER_TO_MEMBER_AUTHORITY
  FOREIGN KEY (MEMBER_ID)
  REFERENCES MEMBER (MEMBER_ID)
);

CREATE TABLE MEMBER_HOBBY
(
  MEMBER_ID TEXT NOT NULL,
  HOBBY_SEQ TEXT NOT NULL,
  CONSTRAINT FK_MEMBER_TO_MEMBER_HOBBY
  FOREIGN KEY (MEMBER_ID)
  REFERENCES MEMBER (MEMBER_ID),
  CONSTRAINT FK_HOBBY_TO_MEMBER_HOBBY
  FOREIGN KEY (HOBBY_SEQ)
  REFERENCES HOBBY (HOBBY_SEQ)
);

CREATE TABLE MULTIBOARD
(
  MULTIBOARD_ID TEXT NOT NULL,
  NAME          TEXT NULL    ,
  GENRE         TEXT NULL    ,
  MEMBER_ID     TEXT NOT NULL,
  PRIMARY KEY (MULTIBOARD_ID),
  CONSTRAINT FK_MEMBER_TO_MULTIBOARD
  FOREIGN KEY (MEMBER_ID)
  REFERENCES MEMBER (MEMBER_ID)
);

CREATE TABLE ORGANIZATION
(
  ORGANIZATION_SEQ  REAL NOT NULL,
  NAME              TEXT NULL    ,
  ORGANIZATION_SEQ1 REAL NULL    ,
  PRIMARY KEY (ORGANIZATION_SEQ),
  CONSTRAINT FK_ORGANIZATION_TO_ORGANIZATION
  FOREIGN KEY (ORGANIZATION_SEQ1)
  REFERENCES ORGANIZATION (ORGANIZATION_SEQ)
);

CREATE TABLE PROJECTS
(
  PROJECTS_SEQ TEXT NOT NULL,
  PROJECTNO    TEXT NULL    ,
  PROJECTNAME  TEXT NULL    ,
  PROJECTTYPE  TEXT NULL    ,
  PROJECTCOST  REAL NULL    ,
  MEMBER_ID    TEXT NOT NULL,
  PRIMARY KEY (PROJECTS_SEQ),
  CONSTRAINT FK_MEMBER_TO_PROJECTS
  FOREIGN KEY (MEMBER_ID)
  REFERENCES MEMBER (MEMBER_ID)
);

CREATE TABLE TEACHER
(
  TEACHER_SEQ REAL NOT NULL,
  MEMBER_ID   TEXT NOT NULL,
  PRIMARY KEY (TEACHER_SEQ),
  CONSTRAINT FK_MEMBER_TO_TEACHER
  FOREIGN KEY (MEMBER_ID)
  REFERENCES MEMBER (MEMBER_ID)
);
