-- SQLite

-- CREATE TABLE COMPANY(
-- ID INT PRIMARY KEY NOT NULL,
-- NAME TEXT NOT NULL,
-- AGE INT NOT NULL,
-- ADDRESS CHAR(50),
-- SALARY REAL

-- );

-- CREATE TABLE DEPARTMENT(
-- ID INT PRIMARY KEY NOT NULL,
-- DEPT CHAR(50) NOT NULL,
-- EMP_ID INT NOT NULL

-- );


-- INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
-- VALUES (1, 'Paul', 32, 'California', 20000.00 );

-- INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
-- VALUES (2, 'Allen', 25, 'Texas', 15000.00 );

-- INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
-- VALUES (3, 'Teddy', 23, 'Norway', 20000.00 );

-- INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
-- VALUES (4, 'Mark', 25, 'Rich-Mond ', 65000.00 );

-- INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
-- VALUES (5, 'David', 27, 'Texas', 85000.00 );

-- INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY) 
-- VALUES (6, 'Kim', 22, 'South-Hall', 45000.00 );

SELECT * FROM COMPANY WHERE AGE >= 25 OR SALARY >= 65000;
SELECT * FROM COMPANY WHERE AGE IS NOT NULL;
SELECT * FROM COMPANY WHERE NAME LIKE 'Ki%';
SELECT * FROM COMPANY WHERE AGE IN (25,27);
SELECT * FROM COMPANY WHERE AGE NOT IN (25,27);
SELECT * FROM COMPANY WHERE AGE BETWEEN 25 AND 27;

SELECT * FROM COMPANY WHERE AGE IN (25) AND SALARY = 65000;

SELECT * FROM COMPANY WHERE AGE>
    SELECT AGE
    FROM COMPANY
    WHERE SALARY >= 65000;

    SELECT AGE
    FROM COMPANY
    WHERE SALARY >= 65000;

SELECT * FROM COMPANY ORDER BY SALARY ASC;
SELECT * FROM COMPANY ORDER BY NAME,SALARY ASC;
SELECT * FROM COMPANY ORDER BY NAME DESC;

SELECT * FROM COMPANY
GROUP BY name
HAVING count(name) <2;

SELECT * FROM COMPANY
GROUP BY name
HAVING count(name) >=2;

SELECT name,SALARY FROM COMPANY;
SELECT DISTINCT name,SALARY FROM COMPANY;

--결측치연습

