-- SQLite

INSERT INTO MEMBER (ID, NAME, AGE, POSITION) VALUES (10,'고상훈',18,'행동대원');
INSERT INTO MEMBER (ID, NAME, AGE, POSITION) VALUES (20,'아사코',15,'행동대장');
INSERT INTO MEMBER (ID, NAME, AGE, POSITION) VALUES (50,'이루다',16,'자금조달');
INSERT INTO MEMBER (ID, NAME, AGE, POSITION) VALUES (80,'김대현',17,'문지기');
INSERT INTO MEMBER (ID, NAME, AGE, POSITION) VALUES (130,'나석주',17,'정보원');


INSERT INTO THINK (ID, VERIFIC) VALUES (10,'불순분자');
INSERT INTO THINK (ID, VERIFIC) VALUES (20,'정상');
INSERT INTO THINK (ID, VERIFIC) VALUES (50,'정직');
INSERT INTO THINK (ID, VERIFIC) VALUES (80,'바른생각');
INSERT INTO THINK (ID, VERIFIC) VALUES (130,'반반');
