-- SQLite
DROP TABLE DEPARTMENT;
DROP TABLE HOBBY;
DROP TABLE MEMBER;
DROP TABLE MEMBER_HOBBY;

CREATE TABLE DEPARTMENT
(
  DEPARTMENT_ID TEXT NOT NULL,
  NAME          TEXT NOT NULL,
  PRIMARY KEY (DEPARTMENT_ID)
);

CREATE TABLE HOBBY
(
  HOBBY_ID TEXT NOT NULL,
  NAME     TEXT NOT NULL,
  PRIMARY KEY (HOBBY_ID)
);

CREATE TABLE MEMBER
(
  MEMBER_ID     TEXT NOT NULL,
  NAME          TEXT NOT NULL,
  AGE           REAL NULL    ,
  ADDRESS       TEXT NULL    ,
  SALARY        REAL NULL    ,
  DEPARTMENT_ID TEXT NOT NULL,
  PRIMARY KEY (MEMBER_ID),
    CONSTRAINT FK_DEPARTMENT_TO_MEMBER
    FOREIGN KEY (DEPARTMENT_ID)
    REFERENCES DEPARTMENT (DEPARTMENT_ID)
);

CREATE TABLE MEMBER_HOBBY
(
  HOBBY_ID  TEXT NOT NULL,
  MEMBER_ID TEXT NOT NULL,
CONSTRAINT FK_HOBBY_TO_MEMBER_HOBBY
    FOREIGN KEY (HOBBY_ID)
    REFERENCES HOBBY (HOBBY_ID),
CONSTRAINT FK_MEMBER_TO_MEMBER_HOBBY
    FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBER (MEMBER_ID)

);