-- SQLite
INSERT INTO DEPARTMENT VALUES('DEP1','IT Billing');
INSERT INTO DEPARTMENT VALUES('DEP2','Engineering');

INSERT INTO HOBBY VALUES('HOBBY1','Walk');
INSERT INTO HOBBY VALUES('HOBBY2','Climbing');
INSERT INTO HOBBY VALUES('HOBBY3','Read');

INSERT INTO MEMBER VALUES('MEM1','Paul',32,'California',20000.00,'DEP1');
INSERT INTO MEMBER VALUES('MEM2','Allen',25,'Texas',15000.00,'DEP2');
INSERT INTO MEMBER VALUES('MEM3','Teddy',23,'Norway',20000.00,'DEP1');
INSERT INTO MEMBER VALUES('MEM4','James',44,'Norway',5000.00,'DEP1');


INSERT INTO MEMBER_HOBBY VALUES('HOBBY1','MEM1');
INSERT INTO MEMBER_HOBBY VALUES('HOBBY2','MEM1');
INSERT INTO MEMBER_HOBBY VALUES('HOBBY3','MEM1');
INSERT INTO MEMBER_HOBBY VALUES('HOBBY1','MEM2');
INSERT INTO MEMBER_HOBBY VALUES('HOBBY3','MEM2');
INSERT INTO MEMBER_HOBBY VALUES('HOBBY2','MEM3');
INSERT INTO MEMBER_HOBBY VALUES('HOBBY3','MEM3');
INSERT INTO MEMBER_HOBBY VALUES('HOBBY1','MEM4');